version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./infra/docker/dockerfiles/prod/web.dockerfile
    depends_on:
      - client
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - rent-app

  client:
    build:
      context: .
      dockerfile: ./infra/docker/dockerfiles/prod/client.dockerfile
    restart: unless-stopped
    networks:
      - rent-app

networks:
  rent-app: { }
