version: '3'

services:
  client:
    build:
      context: .
      dockerfile: ./infra/docker/dockerfiles/dev/client.dockerfile
    hostname: rent-app-client
    ports:
      - "4200:4200"
    volumes:
      - ./rent-app-client/src:/usr/app/src

networks:
  rent-app: { }
