version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./infra/docker/dockerfiles/dev/web.dockerfile
    depends_on:
      - client
      - server
    hostname: rent-app-web
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - rent-app

  client:
    build:
      context: .
      dockerfile: ./infra/docker/dockerfiles/dev/client.dockerfile
    depends_on:
      - server
    restart: unless-stopped
    volumes:
      - $PWD/rent-app-client:/usr/app
    networks:
      - rent-app

  server:
    build:
      context: .
      dockerfile: ./infra/docker/dockerfiles/dev/server.dockerfile
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - ./env/server.env
    volumes:
      - $PWD/rent-app-server:/usr/app
    networks:
      - rent-app

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - ./env/db.env
    volumes:
      - rent-app-db:/var/lib/postgresql/data
    networks:
      - rent-app

volumes:
  rent-app-db: { }

networks:
  rent-app: { }
